name: 'Deployment'

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  build:
    name: 'deployment'
    runs-on: ubuntu-latest
    environment: production

    steps:

    - name: checkout 
      uses: actions/checkout@v2

    - name: install SSH key 
      uses: shimataro/ssh-key-action@v2
      with: 
        key: ${{ secrets.EC2_SSH_KEY}}
        known_hosts: ${{ secrets.EC2_HOSTS }}

    - name: deploying in ec2
      env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ubuntu@18.117.168.125 << 'EOF'
          sudo docker stop myhomecontainer || true
          sudo docker rm myhomecontainer || true
          ls -lrt
          pwd
          sudo docker build -t myhome .  
          sudo docker run --name myhomecontainer -d -p 5000:8000 myhome
        EOF
